# Google Cloud Build configuration: https://cloud.google.com/cloud-build/docs/build-config
# Image building process: https://git.k8s.io/test-infra/config/jobs/image-pushing/README.md

# this must be specified in seconds. If omitted, defaults to 600s (10 mins)
timeout: 1200s

options:
  substitution_option: ALLOW_LOOSE
  machineType: N1_HIGHCPU_32

steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: make
  env:
  - GIT_TAG=$_GIT_TAG
  - PULL_BASE_REF=$_PULL_BASE_REF
  - CLOUDBUILD_REPO=$PROJECT_ID
  args:
  - image-push

substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form
  # vYYYYMMDD-hash, and can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'

tags:
- 'kpromo'
- ${_GIT_TAG}
- ${_PULL_BASE_REF}

images:
- 'gcr.io/$PROJECT_ID/kpromo:$_GIT_TAG'
- 'gcr.io/$PROJECT_ID/kpromo:latest'
- 'gcr.io/$PROJECT_ID/kpromo-auditor:$_GIT_TAG'
- 'gcr.io/$PROJECT_ID/kpromo-auditor:latest'
