# See https://cloud.google.com/cloud-build/docs/build-config
timeout: 1200s

options:
  substitution_option: ALLOW_LOOSE
  machineType: N1_HIGHCPU_32

steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: make
  env:
  - GIT_TAG=$_GIT_TAG
  - PULL_BASE_REF=$_PULL_BASE_REF
  - CLOUDBUILD_REPO=$PROJECT_ID
  args:
  - image-push

substitutions:
  # _GIT_TAG will be filled with a git-based tag for the image, of the form vYYYYMMDD-hash, and
  # can be used as a substitution
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'dev'

tags:
- 'cip'
- ${_GIT_TAG}
- ${_PULL_BASE_REF}

# TODO: Temporarily disabling this check, which is currently failing in
#       postsubmit: https://github.com/kubernetes-sigs/k8s-container-image-promoter/issues/312
#images:
#  - 'gcr.io/$PROJECT_ID/cip:$_GIT_TAG'
#  - 'gcr.io/$PROJECT_ID/cip:latest'
#  - 'gcr.io/$PROJECT_ID/cip-auditor:$_GIT_TAG'
#  - 'gcr.io/$PROJECT_ID/cip-auditor:latest'
